name: habit_tracker
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.1.0
  intl: ^0.18.0
  flutter_slidable: ^2.0.0
  flutter_local_notifications: ^17.0.0
  timezone: ^0.9.0
  shared_preferences: ^2.2.2
  pedometer: ^4.1.1
  flutter_background_service: ^5.0.10
  flutter_background_service_android: ^6.2.7
  permission_handler: ^11.0.0
  firebase_core: ^2.24.0
  cloud_firestore: ^4.14.0
  firebase_auth: ^4.15.0
  timeago: ^3.5.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  connectivity_plus: ^5.0.0
  image_picker: ^1.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutterfire_cli: ^1.3.1
  build_runner: ^2.4.0
  hive_generator: ^2.0.0

flutter:
  uses-material-design: true
